### PR TITLE
feat: add serve and watch command

### PR DESCRIPTION
**Pull request by christianllv**
Related to #70 and #71

### CODE REVIEW

**Comment by christianllv** [comment]
@jaredwray I have some questions about this implementation, but before I will explain the development until now.

1. We have the serve command with some parameters:
```-p --port => Port to serve the site on (Default: 3000)
-o --output => Path of where to output the generated blog be served (Default: blog_output)
-w --watch => Watch for changes and rebuild
--path => "Path of where the blog, config, and template are located (Default: blog)
```

The first question is about the ```watch``` option. Currently, if you don't pass the path parameter we assume the .md files are in ```blog``` folder, is ok?

Second question, when a file change is detected we should re-run build command but right now we have a ```runCli``` method inside ```bin/writr``` that we can't call properly if the user has custom ```config``` file. My suggestion is do a refactor and move all ```runCli``` method to a specific ```site generator``` class. Something like:

```
if(watch) {
	this.bs.watch(`${process.cwd()}/${path}/*.md`, async () => {
		// Here we can rebuild the site using a "generator" class
		new SiteGenerator(this.params).run();
		this.bs.reload();
	});
}
```

Please, let me know your thoughts.

**Comment by jaredwray** [comment]
The first question is about the watch option. Currently, if you don't pass the path parameter we assume the .md files are in blog folder, is ok?

>> yep. please assume that the md files are in the blog folder. 
---

Another note: On the `watch` parameter you should assume to have that set to true by default. 

Second question, when a file change is detected we should re-run build command but right now we have a runCli method inside bin/writr that we can't call properly if the user has custom config file. My suggestion is do a refactor and move all runCli method to a specific site generator class. Something like

>> Yes, please move it to its own site generator class.

**Comment by jaredwray** [comment]
@christianllv - can you resolve the conflict and get the unit tests up to 100%?

**Comment by christianllv** [comment]
Yes, right now I'm working on move everything to SiteGenerator class.

**Comment by christianllv** [comment]
@jaredwray Please check the updated PR.

Includes:

- Refactor of the index file to handle clear methods per each command
- Add new SiteGenerator class to generate the blog output files
- Add more accuracy testing for each file and sceneario
- Use ConsoleMessage as a central log class to remove logs in the test output

Let me know your thoughts. 

Thanks!

**Pull request merged**
